server:
  port: 8077
  address: 127.0.0.1
spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/hta?characterEncoding=UTF-8
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: SMSM_SERVICE
  feign:
    customer:
      client: http://127.0.0.1:8077 
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${server.address}:${spring.application.name}:${server.port}