server:
  port: 80
  servlet:
    context-path: /step02
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: user01pw
    url: jdbc:mysql://database-1.c1h6rbtspqxo.ap-northeast-2.rds.amazonaws.com:3306/mydata?characterEncoding=UTF-8
    username: user01
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
