server:
 port: 8099
 address: 127.0.0.1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/hta?characterEncoding=UTF-8
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/activist/
      suffix: .jsp
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: NKW-SERVICE
  feign:
    customer:
      client: http://127.0.0.1:8099
eureka: 
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${server.address}:${spring.application.name}:${server.port}